version: "3.9"

services:
  rabbitmq:
    image: "rabbitmq:4.0.3-management"
    networks:
      - app
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    volumes:
      - "./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      - "./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json"
      - rabbitmq:/bitnami/rabbitmq/mnesia

    # image: "bitnami/rabbitmq:latest"
    # networks:
    #   - app
    # ports:
    #   - "15672:15672"
    #   - "5672:5672"
    # environment:
    #   - RABBITMQ_PASSWORD=12345
    #   - RABBITMQ_USERNAME=market_data
    #   - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    #   - RABBITMQ_DEFINITIONS_FILE=/etc/rabbitmq/defenitions.json
    #   - RABBITMQ_LOAD_DEFINITIONS=yes
    # volumes:
    #   - "./rabbitmq/defenitions.json:/etc/rabbitmq/defenitions.json"
    #   - rabbitmq:/bitnami/rabbitmq/mnesia

  postgres:
    image: timescale/timescaledb-ha:pg16
    restart: always
    networks:
      - app
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=exchange
      - POSTGRES_USER=exchange
      - POSTGRES_PASSWORD=exchange
    volumes:
      - ./init-db/broker-user.sql:/docker-entrypoint-initdb.d/z_01_broker-user.sql
      - ./init-db/metrics-user.sql:/docker-entrypoint-initdb.d/z_02_metrics-user.sql
      - postgres:/home/postgres/pgdata/data
  
  # exchange:
  #   image: "exchange"
  #   networks:
  #     - app
  #   ports:
  #     - "8081:8081"
  #   logging:
  #     driver: loki
  #     options:
  #       loki-url: http://otel-lgtm:3100/loki/api/v1/push

  # broker:
  #   image: "broker"
  #   networks:
  #     - app
  #   environment:
  #     - ENVIRONMENT=dev
  #   logging:
  #     driver: loki
  #     options:
  #       loki-url: http://otel-lgtm:3100/loki/api/v1/push

networks:
  app:
    driver: bridge

volumes:
  rabbitmq:
  postgres:
  otel-lgtm:
  openobserve:
