exchange:
  websocket: "ws://localhost:8081/ws"
rabbitmq:
  uri: "amqp://market_data:12345@localhost:5672/"
postgresql:
  host: localhost
  port: "5432"
  user: broker
  password: broker
  database: broker
telemetry:
  host: "localhost:4317"
  path: "/"
  auth: "Basic dGVzdEBlbWFpbC5jb206Q29tcGxleHBhc3MjMTIz"

application:
  number-of-traders: 5
  institution-id: test_institution_12345
  order-ticker: 1000
