exchange:
  websocket: "ws://exchange:8081/ws"
rabbitmq:
  uri: "amqp://market_data:12345@rabbitmq:5672/"
postgresql:
  host: postgres
  port: "5432"
  user: broker
  password: broker
  database: broker
telemetry:
  host: "192.168.178.22:4317"
  path: "/"
  auth: "Basic dGVzdEBlbWFpbC5jb206Q29tcGxleHBhc3MjMTIz"

application:
  number-of-traders: 100
  institution-id: test_institution_12345
  order-ticker: 1000
