storage:
  tsdb:
    out_of_order_time_window: 10m

scrape_configs:
  - job_name: 'system-metrics'
    static_configs:
      - targets: ['postgres-exporter:9187', 'cadvisor:8080', 'node-exporter:9100']
